# Site settings
title: "Daniel Hume"
email: "daniel@thehumes.at"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://daniel.thehumes.at" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
